remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: "README.md"
    values:
      links:
        -
          title: GitHub
          url: https://github.com/vanjac/winged
  -
    scope:
      path: "*.html"
    values:
      layout: default
      navigation: "/WingEd/navigation.html"
