//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.7.5.
// resgen.rc

#define IDB_TOOLBAR                         100

#define IDC_KNIFE                           100
#define IDC_DRAW                            101

#define IDM_EDGE_TWIN                       100
#define IDM_NEXT_FACE_EDGE                  101
#define IDM_PREV_FACE_EDGE                  102
#define IDM_TOOL_MENU                       103
#define IDM_SEL_MENU                        104
#define IDM_UNDO                            107
#define IDM_REDO                            108
#define IDM_ERASE                           110
#define IDM_EXTRUDE                         115
#define IDM_FLIP_NORMALS                    116
#define IDM_TOOL_SELECT                     117
#define IDM_TOOL_KNIFE                      119
#define IDM_TOOL_JOIN                       120
#define IDM_CLEAR_SELECT                    121
#define IDM_GRID_DOUBLE                     122
#define IDM_GRID_HALF                       123
#define IDM_TOGGLE_GRID                     124
#define IDM_VIEW_FLY                        125
#define IDM_SAVE_AS                         127
#define IDM_OPEN                            128
#define IDM_SAVE                            129
#define IDM_SPLIT_LOOP                      130
#define IDM_SEL_ELEMENTS                    131
#define IDM_SEL_SOLIDS                      132
#define IDM_DRAW_BKSP                       133
#define IDM_TOOL_POLY                       134
#define IDM_NEW                             135
#define IDM_EXPORT_OBJ                      136
#define IDM_SNAP                            137
#define IDM_DUPLICATE                       138
#define IDM_FOCUS                           139
#define IDM_TRANSFORM_MATRIX                140
#define IDM_NEW_VIEWPORT                    141
#define IDM_ORBIT                           142
#define IDM_VIEW_ORTHO                      143
#define IDM_VIEW_MENU                       144
#define IDM_VIEW_TOP                        145
#define IDM_VIEW_FRONT                      146
#define IDM_VIEW_SIDE                       147
#define IDM_WIREFRAME                       148
#define IDM_PERSPECTIVE                     149
#define IDM_NEW_MATERIAL                    150
#define IDM_ADD_TEXTURE                     151

#define IDR_VERT_UNLIT                      100
#define IDR_FRAG_SOLID                      101
#define IDR_VERT_FACE                       102
#define IDR_FRAG_FACE                       103

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    104
        #define _APS_NEXT_COMMAND_VALUE     152
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
